#!/usr/bin/env node
/* Upwind — test suite.   node tests/run_all.js   (exit code 0 = all passed)
   Sections: syntax facts content home record privacy   (U0: the shell; drills and incidents add their sections in U1 and U2) */
global.window=global.window||{};
const path=require('path'),fs=require('fs'),vm=require('vm');
const ALL=['syntax','facts','content','home','record','privacy','balance','lesson','drills','quiz','gate','clean','mistakes','zones','chaos','smooth','inject','real'];
let want=process.argv.slice(2);if(!want.length)want=ALL;
let failed=0,n=0;const T0=Date.now();
function report(sec,name,ok,detail=''){n++;if(!ok)failed++;console.log(`${ok?'PASS':'FAIL'}  ${sec.padEnd(9)} ${name}${detail?'  — '+detail:''}`);}
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');const {boot}=require('./uw_mock.js');
const sw=fs.readFileSync(path.join(__dirname,'..','sw.js'),'utf8');

if(want.includes('syntax')){try{new vm.Script(html.split('<script>')[1].split('</script>')[0]);report('syntax','index.html script compiles',true);}catch(e){report('syntax','index.html script compiles',false,e.message);}
  {const ver=(html.match(/APP_VERSION='([^']+)'/)||[])[1],cache=(sw.match(/CACHE = '([^']+)'/)||[])[1];
   report('syntax','service-worker cache matches app version',cache===`upwind-v${ver}`,`app ${ver}, cache ${cache}`);
   report('syntax','offline helper clears only its own old caches',/k\.startsWith\('upwind-v'\)/.test(sw)&&!/bls-ready|bleed-control|patient-contact|e102/.test(sw));
   report('syntax','offline helper never caches statistics requests',/goatcounter\\\.com|zgo\\\.at/.test(sw));}
  {// shared core: loaded before the app, listed in the offline cache, header hash matches the body, identical to the hub's copy when checked out next to it
   const cp=path.join(__dirname,'..','preconnect-core.js');const ct=fs.existsSync(cp)?fs.readFileSync(cp,'utf8'):'';const first=ct.split('\n')[0]||'';const body=ct.slice(first.length+1);
   const wantH=(first.match(/sha256:([0-9a-f]{64})/)||[])[1];const got=require('crypto').createHash('sha256').update(body,'utf8').digest('hex');
   const tagOK=html.indexOf('<script src="preconnect-core.js"></script>')>-1&&html.indexOf('<script src="preconnect-core.js"></script>')<html.indexOf('\n<script>\n');
   report('syntax','shared core loaded first, cached offline, header hash matches body',!!ct&&wantH===got&&sw.includes("'preconnect-core.js'")&&tagOK,wantH===got?'hash ok':`hash expected ${got.slice(0,12)}`);
   const hub=path.join(__dirname,'..','..','charge-the-line.github.io','preconnect-core.js');if(fs.existsSync(hub))report('syntax','shared core is byte-identical to the hub copy',fs.readFileSync(hub,'utf8')===ct);}
  {// fonts served from this site; nothing from Google; every file exists and is cached
   const urls=[...new Set([...html.matchAll(/url\((fonts\/[^)]+)\)/g)].map(m=>m[1]))];
   report('syntax','fonts served from this site, cached offline, no request to Google',!/fonts\.googleapis|gstatic\.com/.test(html)&&urls.length>=5&&urls.every(u=>fs.existsSync(path.join(__dirname,'..',u))&&sw.includes(`'${u}'`)),`${urls.length} font files`);}
  {// the statistics snippet, the drill-night bar and the settings sheet are the shared markup
   const snip=html.split('<script data-pca>')[1]||'';
   report('syntax','statistics snippet present, module code uw, pointed at preconnect.goatcounter.com',/window\.PCA_MOD="uw"/.test(snip)&&/preconnect\.goatcounter\.com\/count/.test(snip));
   report('syntax','drill night bar and picker markup present, settings sheet present with every switch',/<div id="pc-drill" class="pc-drillbar hidden" data-hub="\.\.\/"><\/div>/.test(html)&&/id="pc-drillov"/.test(html)&&['text','contrast','motion','sound','haptics','stats'].every(k=>html.includes(`data-set="${k}"`))&&/data-val="day"/.test(html));
   report('syntax','manifest and icons exist',fs.existsSync(path.join(__dirname,'..','manifest.json'))&&fs.existsSync(path.join(__dirname,'..','icon-192.png'))&&fs.existsSync(path.join(__dirname,'..','icon-512.png'))&&/"name": "Upwind"/.test(fs.readFileSync(path.join(__dirname,'..','manifest.json'),'utf8')));}
  {const {api}=boot();report('syntax','boots in the harness; settings and core helpers are reachable',typeof api.settings().sound==='string'&&typeof api.pcSpacing==='function'&&api.APP_VERSION===(html.match(/APP_VERSION='([^']+)'/)||[])[1]);}}

if(want.includes('facts')){const {api}=boot();const M=api.MAT;
  // One materials table. Every entry names its source; anything a drill or incident uses must be checked against the printed book.
  const ids=Object.keys(M);report('facts','every material names its ERG source page and guide',ids.length>=7&&ids.every(k=>M[k].src&&/ERG2024/.test(M[k].src)&&M[k].guide),ids.join(', '));
  const used=new Set();Object.values(api.DRILLS).forEach(d=>(typeof d.mats==='function'?d.mats():d.mats||[]).forEach(m=>used.add(m)));Object.keys(api.SCN).forEach(id=>{if(api.scnReady(id))api.SCN[id].mats.forEach(m=>used.add(m));});
  const unchecked=[...used].filter(m=>!M[m]||!M[m].checked);const locked=Object.keys(api.SCN).filter(id=>!api.scnReady(id));report('facts','every material a live drill or unlocked incident uses has been checked against the printed ERG; an incident with an unchecked material stays locked',unchecked.length===0&&locked.every(id=>api.SCN[id].mats.some(m=>!M[m].checked)),unchecked.length?'unchecked: '+unchecked.join(', '):`${used.size} in use, locked: ${locked.join(', ')||'none'}`);
  report('facts','ammonia carries the lines Max read: Guide 125 (isolate at least 330 ft; tank in fire 1 mile), Table 1 (small spill 100 ft, 0.1 mi) and the Table 3 nurse-tank row (200 ft; day 0.3/0.2/0.2, night 0.9/0.2/0.2 mi), and the incident isolation distance is the nurse-tank row',M.ammonia.checked&&M.ammonia.iso.ft===200&&M.ammonia.t3.nurse.iso.ft===200&&M.ammonia.t3.nurse.day.low===.3&&M.ammonia.t3.nurse.night.low===.9&&M.ammonia.t3.nurse.night.high===.2&&M.ammonia.t1.small.iso.ft===100&&M.ammonia.t1.small.night===.1&&M.ammonia.guideIso&&M.ammonia.guideIso.ft===330&&M.ammonia.guideIso.m===100&&/1 mile/.test(M.ammonia.fire.txt)&&M.ammonia.fire.m===1600&&(M.ammonia.checked?!!(M.ammonia.iso&&M.ammonia.t3&&M.ammonia.t3.nurse):false)&&ids.filter(k=>M[k].checked).every(k=>M[k].iso&&M[k].iso.ft>0),M.ammonia.checked?'checked':'awaiting Table 1 and Table 3');
  report('facts','propane and natural gas carry the Guide 115 lines Max read: isolate 330 ft, large spill half a mile downwind, tank in fire 1 mile',['propane','natgas'].every(k=>M[k].checked&&M[k].iso.ft===330&&M[k].iso.m===100&&M[k].large.m===800&&/half a mile/.test(M[k].large.txt)&&M[k].fire.m===1600&&/1 mile/.test(M[k].fire.txt)&&/Guide 115/.test(M[k].checked)));
  report('facts','chlorine and carbon monoxide carry the Guide 124 and 119 lines, the Table 3 chlorine rows and the Table 1 rows Max read (chlorine small spill 100 ft, 0.1 and 0.3 mi; carbon monoxide small spill 200 ft, 0.2 and 0.9 mi, large 600 ft, 0.7 and 2.4 mi)',M.chlorine.checked&&M.co.checked&&M.chlorine.iso.ft===100&&M.chlorine.t1.small.night===.3&&M.co.iso.ft===200&&M.co.t1.small.day===.2&&M.co.t1.large.iso.ft===600&&M.co.t1.large.night===2.4&&M.chlorine.guideIso.ft===330&&M.chlorine.fire.m===800&&M.chlorine.t3.cyl.iso.ft===500&&M.chlorine.t3.cyl.night.low===1.5&&M.chlorine.t3.rail.day.low===6&&M.co.guideIso.ft===330&&M.co.fire.m===1600&&['chlorine','co'].every(k=>M[k].checked?!!(M[k].iso&&M[k].t1):M[k].iso===null&&/Table 1/.test(M[k].read||'')),['chlorine','co'].map(k=>k+':'+(M[k].checked?'checked':'awaiting Table 1')).join(', '));
  report('facts','vinyl chloride and unknown cargo carry the Guide 116P and 111 lines Max read (both isolate 330 ft; vinyl chloride large spill half a mile and tank in fire 1 mile, marked P for explosive polymerization, no green-table rows; unknown cargo tank in fire half a mile, no large-spill line)',M.vcm.checked&&M.unknown.checked&&M.vcm.iso.ft===330&&M.vcm.iso.m===100&&M.vcm.large.m===800&&M.vcm.fire.m===1600&&/1 mile/.test(M.vcm.fire.txt)&&M.vcm.poly===true&&!M.vcm.tih&&!M.vcm.t1&&!M.vcm.t3&&String(M.vcm.guide)==='116P'&&M.unknown.iso.ft===330&&M.unknown.fire.m===800&&/half a mile/.test(M.unknown.fire.txt)&&!M.unknown.large&&M.unknown.guide===111&&/Guide 116P/.test(M.vcm.checked)&&/Guide 111/.test(M.unknown.checked)&&Object.keys(M).every(k=>M[k].checked),Object.keys(M).filter(k=>!M[k].checked).join(', ')||'every material checked');
  // No distance may be shown anywhere unless it comes from a checked entry: at U0 the page prints no ERG distance at all.
  const vis=html.split('<script>')[0].split('<script data-pca>')[0]+html.split('</script>').pop();
  const js=html.split('<script>')[1];const matBlock=js.slice(js.indexOf('const MAT={'),js.indexOf('};',js.indexOf('const MAT={'))+2);const outside=js.replace(matBlock,'');
  const distances=(outside.match(/\b(\d{2,4}) ?(m|ft|meters|feet|km|mi|miles)\b/g)||[]).filter(x=>!/^(48|44|540|480|390|320|1200|630) /.test(x));
  report('facts','no ERG distance is written anywhere but the materials table (everything else reads from it); gasoline carries Max\'s reading of Guide 128',distances.length===0&&/iso:\{m:50,ft:150\},large:\{m:300,ft:1000\}/.test(matBlock)&&/checked:'2026-10-03 Max, PHMSA ERG app, Guide 128'/.test(matBlock),distances.join(' | ')||'none outside MAT');
  report('facts','the page names the ERG edition and tells people to use their current ERG',api.ERG_ED==='ERG2024'&&/use your department's current ERG or the PHMSA ERG app/.test(html));
  report('facts','meter alarm points are the common defaults and the "know yours" line is there',api.METER.o2lo===19.5&&api.METER.o2hi===23.5&&api.METER.lel===10&&api.METER.co===35&&api.METER.h2s===10&&/Alarm settings vary by meter and department — know yours/.test(html)&&!/Altair|\bMSA\b|Dr[aä]ger|BW Technologies|\bRKI\b|Industrial Scientific/.test(html));}

if(want.includes('content')){
  report('content','the Operations boundary is stated on the home page and in the reference',/isolate, deny entry, call the hazmat team/i.test(html)&&/Operations crews do not enter/.test(html)&&/never teaches hot-zone entry/.test(html));
  report('content','no phone numbers ship until confirmed',!/\(\d{3}\)\s?\d{3}-\d{4}|\b\d{3}[-.]\d{3}[-.]\d{4}\b/.test(html));
  {const {api}=boot();api.els&&0;const about=(()=>{const {api,els}=boot();els['h-about'].onclick();return els['info-b'].innerHTML;})();
   report('content','every local name (the team, the notification list) is marked "to confirm" in About, and the list lives in TO_CONFIRM',api.TO_CONFIRM.length>=2&&/still to confirm with Bay County Emergency Management/.test(about)&&api.TO_CONFIRM.every(t=>about.includes(t.replace(/&/g,'&amp;')))&&/Regional Response Team 3/.test(about));}
  report('content','NFPA 470 section numbers are not shown in the app',!/\b[579]\.\d+\.\d+\b/.test(html)&&/NFPA 470/.test(html));
  report('content','trademark and affiliation notices',/Not affiliated with or endorsed by PHMSA, the NFPA/.test(html)&&/practice, not certification/.test(html)&&/Emergency Response Guidebook ©/.test(html));
  report('content','every overlay has a way back',/id="set-close"/.test(html)&&/id="info-close"/.test(html));
  report('content','wake lock helper present and off at home',/function keepAwake/.test(html)&&/function showHome\(\)\{keepAwake\(false\)/.test(html));}

if(want.includes('home')){const {api,els}=boot();
  const R=api.readiness();report('home','readiness counts nineteen activities (lesson, eight drills, seven incidents, three Real Calls) and starts at zero',R.total===19&&R.done===0&&els['rdy-t'].textContent==='0 of 19 activities'&&els['rdy-n'].textContent==='0%'&&/Start with the lesson/.test(els['rdy-s'].textContent));
  report('home','eight drills and all seven incidents (I-75, the nurse tank, the refill cage, the swim club, the house, the rail car, the white powder) are live; nothing is disabled or marked Soon; nothing is clickable that does not exist',(els.drills.innerHTML.match(/<button/g)||[]).length===8&&(els.incidents.innerHTML.match(/<button/g)||[]).length===7&&!/ disabled/.test(els.drills.innerHTML)&&(els.incidents.innerHTML.match(/ disabled/g)||[]).length===0&&!/disabled/.test(els.incidents.innerHTML.match(/<button class="scen" data-scn="powder"[^>]*>/)[0])&&!/disabled/.test(els.incidents.innerHTML.match(/<button class="scen" data-scn="rail"[^>]*>/)[0])&&!/disabled/.test(els.incidents.innerHTML.match(/<button class="scen" data-scn="pool"[^>]*>/)[0])&&!/disabled/.test(els.incidents.innerHTML.match(/<button class="scen" data-scn="house"[^>]*>/)[0])&&!/disabled/.test(els.incidents.innerHTML.match(/<button class="scen" data-scn="propane"[^>]*>/)[0])&&!/disabled/.test(els.incidents.innerHTML.match(/<button class="scen" data-scn="i75"[^>]*>/)[0])&&!/disabled/.test(els.incidents.innerHTML.match(/<button class="scen" data-scn="nurse"[^>]*>/)[0])&&!/>Soon</.test(els.drills.innerHTML)&&(els.incidents.innerHTML.match(/>Soon</g)||[]).length===0&&!/disabled/.test(html.match(/<button class="scen" id="h-learn"[^>]*>/)[0])&&/Tanker on its side, I-75/.test(els.incidents.innerHTML));
  report('home','three tiers, Guided by default, the help line changes',api.TIER()===0&&/ERG distances are drawn on the map/.test(els.tierhelp.textContent));
  els['h-ref'].onclick();const ref=els['info-b'].innerHTML;report('home','pocket reference: ERG order, three zones, the generic meter, the always-right line, and no distances',/The ERG, in order/.test(ref)&&/Hot:/.test(ref)&&/Warm:/.test(ref)&&/Cold:/.test(ref)&&/19.5% low · 23.5% high/.test(ref)&&/Isolate. Deny entry. Call the hazmat team./.test(ref)&&/Distances are not listed here on purpose/.test(ref)&&!/\b\d+ ?(ft|m|mile|km)\b/.test(ref));
  report('home','ERG edition printed into the intro card',els['erg-ed'].textContent==='ERG2024');
  {const a=boot();a.els['b-inst'].onclick();const on=a.api.INST()&&JSON.parse(a.store.upwind).inst===true&&a.els['b-inst'].textContent==='Instructor mode: on';const b=boot({upwind:JSON.stringify({inst:true,runs:[]})});report('home','instructor switch saves and is remembered at boot',on&&b.api.INST()===true&&b.els['b-inst'].classList.contains('on'));}
  {const c=boot({'preconnect-drill':JSON.stringify({on:true,inst:'Max',roster:['Jo'],who:'Jo',start:new Date().toISOString()})});report('home','drill night: the switch reads on (Drill Night) without being set, and the bar binds',c.api.instOn()===true&&c.els['b-inst'].textContent==='Instructor mode: on (Drill Night)'&&!c.els['pc-drill'].classList.contains('hidden'));}}

if(want.includes('record')){const {api,store}=boot();api.record('drill','placard',88);api.record('scenario','i75',72,{variant:'B'});const R=JSON.parse(store.upwind).runs;
  report('record','runs save under the upwind key in the shared shape (kind, id, score, d, tier, variant)',R.length===2&&R[0].kind==='drill'&&R[0].id==='placard'&&R[0].score===88&&R[0].tier===0&&R[1].variant==='B'&&/^\d{4}-\d\d-\d\dT/.test(R[1].d));
  const b=boot({'preconnect-drill':JSON.stringify({on:true,inst:'Max',roster:['Jo'],who:'Jo',start:'2026-10-03T18:00:00.000Z'})});b.api.record('drill','erg',90);const r=JSON.parse(b.store.upwind).runs[0];
  report('record','on a drill night every run is stamped with who, the instructor and the night',r.who[0]==='Jo'&&r.inst==='Max'&&r.night==='2026-10-03T18:00:00.000Z');
  const c=boot({upwind:JSON.stringify({runs:[{kind:'drill',id:'placard',score:88,d:new Date().toISOString(),tier:0}]})});report('record','readiness and the home chips read saved best scores',c.api.readiness().done===1&&/id="chip-placard">88</.test(c.els.drills.innerHTML));
  const d=boot({upwind:JSON.stringify({runs:[{kind:'drill',id:'placard',score:88,d:'2026-10-03T10:00:00.000Z',tier:0}],name:'Jo',dept:'MTFD'})});d.els['h-prog'].onclick();d.els['p-name'].value='Jo';d.els['p-dept'].value='MTFD';d.els['p-csv'].onclick();
  report('record','progress screen and CSV list the saved run with a readable name',/not yet/.test(d.els['info-b'].innerHTML)&&/Placard ID/.test(global.__csv)&&/"Jo","MTFD","Drill","Placard ID"/.test(global.__csv));}

if(want.includes('privacy')){// the statistics snippet alone: names and typed text cannot survive into an event path; the opt-out stops everything
  const snip=html.split('<script data-pca>')[1].split('</script>')[0];const W={addEventListener(){}},sent=[];global.window=W;global.localStorage={getItem:()=>null};global.document={createElement:()=>({setAttribute(){}}),head:{appendChild(){}}};
  new Function(snip)();W.goatcounter={count:o=>sent.push(o.path)};W.PCA.ev('uw/finish/i75/Max Tester said "hi" <b>');W.PCA.flush();
  report('privacy','event paths are cleaned to safe characters and carry the uw module code',/^[a-z0-9\/\-]+$/.test(sent[0]||'x ')&&W.PCA.mod==='uw',sent[0]);
  report('privacy','scores are reported only as coarse bands',W.PCA.bkt(97)==='score-90-100'&&W.PCA.bkt(83)==='score-80s'&&W.PCA.bkt(12)==='score-under-60');
  const W2={addEventListener(){}},sent2=[];global.window=W2;global.localStorage={getItem:k=>k==='preconnect-stats'?'off':null};new Function(snip)();W2.goatcounter={count:o=>sent2.push(o.path)};W2.PCA.ev('uw/start/i75');W2.PCA.flush();
  report('privacy','the Privacy page opt-out stops every event',W2.PCA.off===true&&sent2.length===0);
  report('privacy','no name, organization or typed text is ever put into an event by the app',!/pca\([^)]*(name|dept|org|who|inst\b)/.test(html.split('<script>')[1]));}


if(want.includes('balance')){const {api}=boot();let lo=0,sh=0,tot=0;const chk=(arr,gi)=>{const L=arr.map(x=>x.length);tot++;if(L[gi]===Math.max(...L))lo++;else if(L[gi]===Math.min(...L))sh++;};
  api.LESSON.forEach(s=>chk(s.o.map(x=>x[0]),s.o.findIndex(x=>x[1]==='good')));for(let i=0;i<20;i++)for(const k in api.DRILLS)api.DRILLS[k].bank().forEach(q=>chk([q.a,...q.d],0));
  report('balance','right answer not usually the longest (lesson + 20 generations of every drill)',lo/tot<=.45,`${lo} of ${tot}`);report('balance','right answer not usually the shortest',sh/tot<=.45,`${sh} of ${tot}`);
  {let lo=0,sh=0,tot=0;const {standIn}=require('./uw_bot.js');standIn(api);for(const id in api.SCN)for(const V of api.VARIANTS[id])api.SCN[id].build(V).steps.filter(x=>x.k==='decide').forEach(x=>{const L=x.o.map(o=>o[0].length),gi=x.o.findIndex(o=>o[1]==='good');tot++;if(L[gi]===Math.max(...L))lo++;else if(L[gi]===Math.min(...L))sh++;});
   report('balance','incident decisions: the right call is not usually the longest or the shortest option (every incident, every layout)',lo/tot<=.45&&sh/tot<=.45,`${lo} longest, ${sh} shortest of ${tot}`);}}

if(want.includes('lesson')){for(const mode of ['right','wrong']){const {api,els,store}=boot();api.lessonStart();let g=0;while(api.LS()&&g++<60){const L=api.LS(),s=api.LESSON[L.i];if(mode==='wrong'&&L.first[L.i]===undefined)api.lessonAct({l:'ans',k:String(s.o.findIndex(x=>x[1]!=='good'))});api.lessonAct({l:'ans',k:String(s.o.findIndex(x=>x[1]==='good'))});api.lessonAct({l:'next'});}
   const r=JSON.parse(store.upwind).runs[0];report('lesson',`all ${api.LESSON.length} slides; first-try ${mode} scores ${mode==='right'?100:0} and is recorded`,String(els['done-s'].textContent)===(mode==='right'?'100':'0')&&r&&r.kind==='lesson'&&r.score===(mode==='right'?100:0)&&!els.doneov.classList.contains('hidden'),'score '+els['done-s'].textContent);}
  {const {api,els}=boot();api.lessonStart();api.lessonAct({l:'next'});const stuck=api.LS().i===0;api.lessonAct({l:'ans',k:String(api.LESSON[0].o.findIndex(x=>x[1]==='good'))});api.lessonAct({l:'next'});report('lesson','the check must be answered before Next works',stuck&&api.LS().i===1);
   api.lessonAct({l:'quit'});report('lesson','Leave the lesson closes it and returns home',api.LS()===null&&els.lessonov.classList.contains('hidden'));}
  report('lesson','twelve slides, each with pts, a question, exactly one good option and a why; the "know yours" line is in the meter slide',api=>true&&(()=>{const {api}=boot();return api.LESSON.length===12&&api.LESSON.every(s=>s.pts.length>=3&&s.q&&s.o.filter(x=>x[1]==='good').length===1&&s.o.length===3&&s.why)&&api.LESSON.some(s=>s.pts.join(' ').includes('Alarm settings vary by meter and department — know yours'))})());}

if(want.includes('drills')){const {api}=boot();const ids=['placard','erg','container','nfpa704','zones','meter','shelter','ppe'];
  report('drills','eight drills, each bank gives at least eight distinct questions with three options, the answer among them, and a why',ids.every(k=>api.DRILLS[k])&&ids.every(k=>{for(let i=0;i<5;i++){const b=api.DRILLS[k].bank();if(b.length<8||new Set(b.map(q=>q.q)).size!==b.length||!b.every(q=>q.d.length===2&&!q.d.includes(q.a)&&q.why&&q.q))return false;}return true;}));
  // independent recalculation: a second copy of the facts in the test, never the app's own table
  const CLS={'Explosives':'1','Flammable gas':'2.1','Non-flammable gas':'2.2','Toxic gas':'2.3','Flammable liquid':'3','Flammable solid':'4.1','Spontaneously combustible':'4.2','Dangerous when wet':'4.3','Oxidizer':'5.1','Organic peroxide':'5.2','Poison':'6.1','Radioactive':'7','Corrosive':'8','Miscellaneous hazard':'9'};
  let okP=true,nP=0;for(let i=0;i<30;i++)api.DRILLS.placard.bank().forEach(q=>{const m=q.q.match(/bottom of a (.+) placard/);if(m){nP++;const name=Object.keys(CLS).find(n=>n.toLowerCase()===m[1]);if(CLS[name]!==q.a)okP=false;}const k=q.q.match(/is (orange|red|green|white|blue|yellow|black)/);if(/What is the hazard/.test(q.q)){nP++;const look=q.q;const want=look.includes('green')?'Non-flammable gas':look.includes('blue with')?'Dangerous when wet':look.includes('yellow with a flaming')?'Oxidizer':look.includes('red over yellow')?'Organic peroxide':look.includes('yellow over white')?'Radioactive':look.includes('orange')?'Explosives':look.includes('flame and a 3')?'Flammable liquid':look.includes('red with a flame and a 2')?'Flammable gas':look.includes('skull and crossbones and a 2')?'Toxic gas':look.includes('skull and crossbones and a 6')?'Poison':look.includes('stripes with a flame')?'Flammable solid':look.includes('white over red')?'Spontaneously combustible':look.includes('test tubes')?'Corrosive':look.includes('black and white')?'Miscellaneous hazard':null;if(want!==q.a)okP=false;}});
  report('drills','placard keys match an independent class table (30 generations)',okP&&nP>150,`${nP} checked`);
  const M={o2lo:19.5,o2hi:23.5,lel:10,co:35,h2s:10};let okM=true,nM=0;for(let i=0;i<40;i++)api.DRILLS.meter.bank().forEach(q=>{const m=q.q.match(/O₂ ([\d.]+)%, LEL ([\d.]+)%, CO ([\d.]+) ppm, H₂S ([\d.]+) ppm/);if(!m)return;nM++;const [o2,lel,co,h2s]=m.slice(1).map(Number);const want=o2<M.o2lo?'Oxygen is low':o2>M.o2hi?'Oxygen is high':lel>=M.lel?'Flammable gas':co>M.co?'Carbon monoxide':h2s>M.h2s?'Hydrogen sulfide':'Readings are normal';if(!q.a.startsWith(want))okM=false;});
  report('drills','meter keys match an independent read of the default alarm points (40 generations)',okM&&nM>150,`${nM} checked`);
  const C=['north','northeast','east','southeast','south','southwest','west','northwest'];let okZ=true,nZ=0;for(let i=0;i<30;i++)api.DRILLS.zones.bank().forEach(q=>{let m=q.q.match(/Wind is out of the (\w+)\. The leak/);if(m){nZ++;if(q.a!==`The ${m[1]} side, upwind`)okZ=false;}m=q.q.match(/Wind is out of the (\w+)\. Which way/);if(m){nZ++;const i=C.indexOf(m[1]);if(q.a!==`Toward the ${C[(i+4)%8]}`)okZ=false;}});
  report('drills','zone keys match an independent compass (30 generations)',okZ&&nZ>100,`${nZ} checked`);
  let ok7=true,n7=0;for(let i=0;i<30;i++)api.DRILLS.nfpa704.bank().forEach(q=>{const m=q.q.match(/blue (\d), red (\d), yellow (\d)/);if(!m)return;n7++;const v=m.slice(1).map(Number);const top=['Health','Fire','Instability'][v.indexOf(Math.max(...v))];if(q.a!==top)ok7=false;});
  report('drills','704 keys match an independent reading of the highest field (30 generations)',ok7&&n7>100,`${n7} checked`);
  {let okE=true,nG=0;const seen=new Set();const want={'UN1203, Gasoline':'128','UN1005, Ammonia, anhydrous':'125','UN1978, Propane':'115','UN1971, Natural gas, compressed (methane)':'115','UN1017, Chlorine':'124','UN1016, Carbon monoxide, compressed':'119','UN1086, Vinyl chloride, stabilized':'116P'};for(let i=0;i<20;i++){const erg=api.DRILLS.erg.bank();erg.forEach(q=>{if(!/which guide\?/.test(q.q))return;nG++;const k=Object.keys(want).find(w=>q.q.startsWith(w));if(!k||q.a!==want[k]||q.d.length!==2||q.d.includes(q.a)||q.d[0]===q.d[1])okE=false;else seen.add(k);});}
  report('drills','the ERG drill asks about the workflow plus one guide question per checked material with a UN number (gasoline 128, propane and natural gas 115, ammonia 125, chlorine 124, carbon monoxide 119, vinyl chloride 116P; unknown cargo has no UN number and gets no question), each with two distinct wrong guide numbers',okE&&nG>0&&seen.size===7&&api.DRILLS.erg.mats().join()==='gasoline,propane,natgas,ammonia,chlorine,co,vcm,unknown',`${nG} guide questions in 20 banks`);
  {const keep={};for(const k in api.MAT){keep[k]=api.MAT[k].checked;api.MAT[k].checked=null;}const erg=api.DRILLS.erg.bank();report('drills','with nothing checked the ERG drill asks about the workflow only, no guide numbers',erg.every(q=>!/which guide\?/.test(q.q))&&api.DRILLS.erg.mats().length===0);for(const k in api.MAT)api.MAT[k].checked=keep[k];}}
  report('drills','no drill question or answer carries an ERG distance',ids.every(k=>api.DRILLS[k].bank().every(q=>!/\b\d{2,4} ?(m|ft|meters|feet|km|mi|miles)\b/.test(q.q+' '+q.a+' '+q.d.join(' ')))));}

if(want.includes('quiz')){{const {api,els,store}=boot();api.drillStart('meter');const Z=api.QZ();const n=Z.qs.length;for(let i=0;i<n;i++){const q=Z.qs[i];api.quizAct({q:'ans',i:String(q.ord.indexOf(q.a))});api.quizAct({q:'next'});}
   const r=JSON.parse(store.upwind).runs[0];report('quiz','a drill played right scores 100, shows the result and is recorded',Z.score===100&&r.kind==='drill'&&r.id==='meter'&&r.score===100&&/100/.test(els['qz-body'].innerHTML));}
  {const {api,store}=boot();api.drillStart('ppe');const Z=api.QZ();Z.qs.forEach(q=>{api.quizAct({q:'ans',i:String((q.ord.indexOf(q.a)+1)%3)});api.quizAct({q:'next'});});report('quiz','a drill played wrong scores 0',Z.score===0&&JSON.parse(store.upwind).runs[0].score===0);}
  {const {api,els}=boot();api.drillStart('placard');const Z=api.QZ();const first=Z.qs[0].ord.slice();api.quizAct({q:'ans',i:'0'});api.quizAct({q:'ans',i:'1'});report('quiz','options are shuffled once and a second tap on the same question is ignored',Z.qs[0].ord.join()===first.join()&&Z.right<=1&&Z.i===0);
   api.quizAct({q:'quit'});report('quiz','Quit closes the drill and goes home',api.QZ()===null&&els.quizov.classList.contains('hidden'));}
  {global.__loc={search:'?drill=placard'};const a=boot();global.__loc={search:'?drill=nope'};const b=boot();global.__loc=undefined;report('quiz','daily-drill deep link: ?drill=placard opens the drill on load; an unknown id is ignored',!!a.api.QZ()&&a.api.QZ().id==='placard'&&!a.els.quizov.classList.contains('hidden')&&!b.api.QZ());}
  {const c=boot({upwind:JSON.stringify({runs:[{kind:'drill',id:'erg',score:90,d:new Date(Date.now()-10*864e5).toISOString(),tier:0},{kind:'lesson',id:'lesson',score:40,d:new Date(Date.now()-2*864e5).toISOString(),tier:0}]})});report('quiz','home chips turn to Due and Again from the spacing rule, and the readiness line counts them',/id="chip-erg">Due</.test(c.els.drills.innerHTML)&&c.els['chip-lesson'].textContent==='Again'&&/2 due for review/.test(c.els['rdy-s'].textContent));}
  {const snip=[];const {api}=boot();const W=global.window;W.PCA={begin:(m,a)=>snip.push('begin:'+m+'/'+a),end:d=>snip.push('end:'+d),abandon:()=>snip.push('abandon'),bkt:n=>'score-'+n,err(){}};api.drillStart('zones');api.quizAct({q:'quit'});api.lessonStart();api.lessonAct({l:'quit'});delete W.PCA;
   report('quiz','statistics: a drill and the lesson send begin and abandon with the uw code and never a name',snip.join()==='begin:uw/drill-zones,abandon,begin:uw/lesson,abandon');}}


if(want.includes('gate')){const {api,els}=boot();api.MAT.gasoline.checked=null;api.homeRender();report('gate','an incident whose material is not checked is built but locked: listed with Soon, disabled, and runStart refuses',!!api.SCN.i75&&!api.scnReady('i75')&&/data-scn="i75"[^>]*disabled/.test(els.incidents.innerHTML)&&/unlocks when its ERG lines/.test(els.incidents.innerHTML)&&(api.runStart('i75'),api.S()===null));
  {const a=api.MAT.ammonia;const keep={checked:a.checked,iso:a.iso,t3:a.t3};a.checked='2026-10-03 test';a.iso=null;a.t3=null;api.homeRender();const stillLocked=!api.scnReady('nurse')&&/data-scn="nurse"[^>]*disabled/.test(els.incidents.innerHTML)&&(api.runStart('nurse'),api.S()===null);require('./uw_bot.js').standIn(api);api.homeRender();const open=api.scnReady('nurse')&&!/data-scn="nurse"[^>]*disabled/.test(els.incidents.innerHTML);Object.assign(a,keep);report('gate','the nurse tank stays locked with a checked stamp alone; it needs the Table 3 isolation distance and protect rows, then it unlocks',stillLocked&&open);}
  api.MAT.gasoline.checked='2026-10-03 test';api.homeRender();report('gate','once the material is checked the incident unlocks and the debrief names the edition, guide and reader',api.scnReady('i75')&&!/data-scn="i75"[^>]*disabled/.test(els.incidents.innerHTML)&&(()=>{const r=require('./uw_bot.js').play('i75',0);return r.ok&&/ERG2024, Guide 128, read on 2026-10-03 test/.test(r.body);})());}

if(want.includes('clean')){const {play}=require('./uw_bot.js');for(const v of ['A','B','C'])for(const tier of [0,1,2]){const r=play('i75',tier,{variant:v});report('clean',`i75 layout ${v} on ${['Guided','Recall','Chaos'][tier]}: a competent crew at human pace scores 100 and the run is recorded with its layout`,r.ok&&r.score===100&&JSON.parse(r.store.upwind).runs[0].variant===v&&JSON.parse(r.store.upwind).runs[0].tier===tier,`score ${r.score}, steps ${r.steps.length}`);}
  for(const v of ['A','B','C'])for(const tier of [0,1,2]){const r=play('nurse',tier,{variant:v});report('clean',`nurse tank layout ${v} on ${['Guided','Recall','Chaos'][tier]}: a competent crew scores 100${v==='C'?' (the farmer talked out of the cloud)':''}`,r.ok&&r.score===100&&JSON.parse(r.store.upwind).runs[0].id==='nurse'&&JSON.parse(r.store.upwind).runs[0].variant===v&&(v!=='C'||r.steps.includes('decide:victim')),`score ${r.score}, steps ${r.steps.length}`);}
  for(const v of ['A','B','C'])for(const tier of [0,1,2]){const r=play('propane',tier,{variant:v});report('clean',`refill cage layout ${v} on ${['Guided','Recall','Chaos'][tier]}: a competent crew scores 100${v==='B'?' (fire on the tank: unmanned streams, withdraw, evacuate the mile)':''}`,r.ok&&r.score===100&&JSON.parse(r.store.upwind).runs[0].id==='propane'&&JSON.parse(r.store.upwind).runs[0].variant===v&&(v!=='B'||(r.steps.includes('decide:relief')&&r.steps.includes('decide:evac'))),`score ${r.score}, steps ${r.steps.length}`);}
  for(const v of ['A','B','C'])for(const tier of [0,1,2]){const r=play('rail',tier,{variant:v});report('clean',`rail car layout ${v} on ${['Guided','Recall','Chaos'][tier]}: a competent crew scores 100${v==='B'?' (relief valve burning, no water: withdraw, let it burn, evacuate the fire distance)':''}`,r.ok&&r.score===100&&JSON.parse(r.store.upwind).runs[0].id==='rail'&&JSON.parse(r.store.upwind).runs[0].variant===v&&r.steps.includes('decide:trains')&&(v==='B'?(r.steps.includes('decide:water')&&r.steps.includes('decide:evac')&&!r.steps.includes('decide:vapor')):(r.steps.includes('decide:vapor')&&r.steps.includes('decide:culvert')&&r.steps.includes(v==='A'?'decide:elevator':'decide:crossing'))),`score ${r.score}, steps ${r.steps.length}`);}
  for(const v of ['A','B','C'])for(const tier of [0,1,2]){const r=play('powder',tier,{variant:v});report('clean',`white powder layout ${v} on ${['Guided','Recall','Chaos'][tier]}: a competent crew scores 100 with no zones step (the room and the building are the perimeter)`,r.ok&&r.score===100&&JSON.parse(r.store.upwind).runs[0].id==='powder'&&JSON.parse(r.store.upwind).runs[0].variant===v&&!r.steps.includes('zones')&&['decide:caller','decide:meter','decide:hvac','decide:test','decide:exposed'].every(x=>r.steps.includes(x))&&r.steps.includes({A:'decide:building',B:'decide:sort',C:'decide:sick'}[v])&&/Guide 111/.test(r.body),`score ${r.score}, steps ${r.steps.length}`);}
  {const r=play('powder',2,{variant:'A',dwell:40});report('clean','white powder on Chaos: instead of a wind shift, a second envelope turns up; no zones step is ever re-opened indoors, and a crew that leaves it unopened scores 100',r.ok&&r.score===100&&r.steps.includes('decide:mail')&&!r.steps.includes('zones')&&/A second envelope/.test(r.body),r.steps.join(' '));}
  {const {boot}=require('./uw_mock.js');const {api,els}=boot();global.__T=1000;const map={};for(const id of ['i75','nurse','propane','pool','house','rail','powder']){api.runStart(id);map[id]=els['uw-map'].innerHTML;api.runAct({r:'quit'});}const lab=id=>(map[id].match(/font-size="9" text-anchor="middle" font-family="Saira Condensed">([^<]*)</g)||[]).map(x=>x.replace(/.*>/,'').replace(/<$/,''));
   report('clean','every map names its own source: TANKER only on I-75; NURSE TANK, BULK TANK · CAGE, PUMP ROOM, HOUSE, TANK CAR, ENVELOPE elsewhere; each source label appears once (no label printed on top of another)',/>TANKER</.test(map.i75)&&/rotate\(20\)/.test(map.i75)&&['nurse','propane','pool','house','rail','powder'].every(id=>!/>TANKER</.test(map[id]))&&/>NURSE TANK</.test(map.nurse)&&lab('propane').filter(x=>x==='BULK TANK · CAGE').length===1&&lab('pool').filter(x=>x==='PUMP ROOM').length===1&&lab('house').filter(x=>x==='HOUSE').length===1&&!/rx="7"/.test(map.house)&&/>TANK CAR</.test(map.rail)&&/rotate\(0\)/.test(map.rail)&&/>SIDING</.test(map.rail)&&/>MAIN LINE</.test(map.rail)&&/>(ENVELOPE|MAILER)</.test(map.powder)&&/>(INSURANCE OFFICE|PARCEL STORE)</.test(map.powder),Object.keys(map).map(id=>id+':'+lab(id).length).join(' '));}
  for(const id of ['pool','house'])for(const v of ['A','B','C'])for(const tier of [0,1,2]){const r=play(id,tier,{variant:v});report('clean',`${id==='pool'?'swim club':'house'} layout ${v} on ${['Guided','Recall','Chaos'][tier]}: a competent crew scores 100`,r.ok&&r.score===100&&JSON.parse(r.store.upwind).runs[0].id===id&&JSON.parse(r.store.upwind).runs[0].variant===v,`score ${r.score}, steps ${r.steps.length}`);}
  {const {play}=require('./uw_bot.js');const seen=new Set();for(let i=0;i<30;i++)seen.add(play('i75',0,{fast:true}).api.VARIANTS.i75.length&&JSON.parse(play('i75',0,{fast:true}).store.upwind).runs[0].variant);report('clean','random play covers all three layouts; a Drill Night pins A',seen.size===3&&(()=>{const r=play('i75',0,{store:{'preconnect-drill':JSON.stringify({on:true,inst:'Max',roster:['Jo'],who:'Jo',start:new Date().toISOString()})}});const run=JSON.parse(r.store.upwind).runs[0];return run.variant==='A'&&run.who[0]==='Jo';})(),[...seen].join(''));}}

if(want.includes('mistakes')){const {play}=require('./uw_bot.js');
  for(const [label,o,chk] of [['approaching from downwind',{route:'down'},r=>r.score<=85&&/downwind/.test(r.body)],['approaching crosswind along the ditch',{route:'cross'},r=>r.score<=95&&/ditch/.test(r.body)],['skipping the bump test',{choiceAt:{bump:'bad'}},r=>r.score<=90&&/tested last shift|smell gasoline/i.test(r.body)&&/Meter bump test/.test(r.body)],['walking into the pool to plug the tank (the Operations boundary)',{choiceAt:{drain:'ops'}},r=>r.score<=70&&/Hot-zone entry is not an Operations task/.test(r.body)],['sending the driver in to close the valves (the Operations boundary)',{choiceAt:{driver:'ops'}},r=>r.score<=70&&/Hot-zone entry/.test(r.body)],['leaving the drain to the team: called correct to call, named as a defensive action missed',{choiceAt:{drain:'missed'}},r=>r.score===95&&/Defensive actions missed:<\/b> Dike the storm drain/.test(r.body)],['never requesting the team, by button or by radio',{noTeam:true,notifySkipTeam:true},r=>r.score<=80&&/never requested/.test(r.body)&&/Left out: Request the regional hazmat team/.test(r.body)],['missing things you could see',{binoMiss:true},r=>r.score<100&&/Missed 4 things/.test(r.body)],['the wrong guide',{ergWrong:true},r=>r.score<=90&&/Wrong guide/.test(r.body)],['a hot zone short of the ERG distance',{hot:100},r=>r.score<=90&&/short of the ERG distance/.test(r.body)],['staging downwind',{stageDownwind:true},r=>r.score<=90&&/staging is not upwind/.test(r.body)],['staging inside the warm zone (inside the isolation distance, so the vapor clock runs)',{stageInside:true},r=>r.score<=88&&/inside the warm zone/.test(r.body)&&/Spent \d+ seconds in the vapor or inside the isolation distance/.test(r.body)],['leaving the team off the notifications and putting the driver\'s name on the air',{notifyMiss:true,notifyExtra:true},r=>r.score<=70&&/Left out/.test(r.body)&&/Does not go over the air/.test(r.body)]]){const r=play('i75',1,o);report('mistakes',`${label} is caught and explained`,r.ok&&chk(r),`score ${r.score}`);}
  for(const [label,v,o,chk] of [['trusting a zero on the 4-gas for ammonia',"A",{choiceAt:{meter:'bad'}},r=>r.score<=90&&/Right call: Nothing\. It has no ammonia sensor/.test(r.body)&&/The 4-gas reading/.test(r.body)],['sending a crew in on air to close the valve (the Operations boundary)',"A",{choiceAt:{fog:'ops'}},r=>r.score<=70&&/Hot-zone entry is not an Operations task: Send two firefighters in on air/.test(r.body)],['leaving the cloud to the team: named as a defensive action missed',"A",{choiceAt:{fog:'missed'}},r=>r.score===95&&/Defensive actions missed:<\/b> Knock the cloud down with fog from upwind and dike the runoff/.test(r.body)],['a straight stream on the leaking fitting',"A",{choiceAt:{fog:'bad'}},r=>r.score<=90&&/ices it and makes more vapor/.test(r.body)],['sending the family through the cloud when it is already on the house (layout A: shelter)',"A",{choiceAt:{house:'bad'}},r=>r.score<=90&&/Right call: Shelter in place/.test(r.body)&&/protective distance here is 0\.3 miles/.test(r.body)],['sheltering a house that has a road out before the cloud arrives (layout B: evacuate)',"B",{choiceAt:{house:'bad'}},r=>r.score<=90&&/Right call: Evacuate them now, out the crosswind road/.test(r.body)&&/night protective action distance at 0\.2 miles in this wind/.test(r.body)],['driving through the cloud to the farmhouse (the Operations boundary)',"A",{choiceAt:{house:'ops'}},r=>r.score<=70&&/Hot-zone entry/.test(r.body)&&/Driving into the cloud/.test(r.body)],['going in on air for the farmer (the Operations boundary, layout C)',"C",{choiceAt:{victim:'ops'}},r=>r.score<=70&&/Structural gear does not stop ammonia/.test(r.body)&&/The farmer in the cloud/.test(r.body)],['putting the farmer in the ambulance before decon',"A",{choiceAt:{decon:'bad'}},r=>r.score<=90&&/Right call: Emergency decon upwind now/.test(r.body)&&/Emergency decon/.test(r.body)],['leaving the co-op and the farm agency off the first report',"A",{notifyMiss:true},r=>r.score<=80&&/Left out: [^<]*(co-op|farm chemical)/.test(r.body)]]){const r=play('nurse',1,Object.assign({variant:v},o));report('mistakes',`nurse tank: ${label} is caught and explained`,r.ok&&chk(r),`score ${r.score}`);}
  for(const [label,v,o,chk] of [['letting the cars finish fueling in the cloud',"A",{choiceAt:{ignition:'bad'}},r=>r.score<=90&&/Right call: Hit the emergency fuel shutoff/.test(r.body)&&/Ignition sources/.test(r.body)],['walking in to close the cylinder valve (the Operations boundary)',"A",{choiceAt:{vapor:'ops'}},r=>r.score<=70&&/Hot-zone entry is not an Operations task: Walk in and close the cylinder valve/.test(r.body)],['leaving the vapor to the team: named as a defensive action missed',"A",{choiceAt:{vapor:'missed'}},r=>r.score===95&&/Defensive actions missed:<\/b> Break the cloud up with fog from upwind/.test(r.body)],['letting the drivers start their cars inside the isolation distance',"A",{choiceAt:{pumps:'bad'}},r=>r.score<=90&&/Right call: Pumps off, everyone out on foot upwind/.test(r.body)],['rolling the hissing cylinder out from under the car (the Operations boundary, layout C)',"C",{choiceAt:{pumps:'ops'}},r=>r.score<=70&&/That cylinder is the source/.test(r.body)],['putting out the cylinder fire that is heating the tank (layout B)',"B",{choiceAt:{fire:'bad'}},r=>r.score<=90&&/Do not extinguish it unless the leak can be stopped/.test(r.body)&&/Fire on the tank/.test(r.body)],['sending a crew under the flame (the Operations boundary, layout B)',"B",{choiceAt:{fire:'ops'}},r=>r.score<=70&&/Hot-zone entry/.test(r.body)&&/next to a heating pressure vessel/.test(r.body)],['keeping crews on the nozzles as the relief valve screams (layout B)',"B",{choiceAt:{relief:'bad'}},r=>r.score<=90&&/Right call: Withdraw everyone now/.test(r.body)&&/The relief valve/.test(r.body)],['sheltering people inside the fire distance of a tank in fire (layout B)',"B",{choiceAt:{evac:'bad'}},r=>r.score<=90&&/Right call: Start evacuating the fire distance/.test(r.body)&&/1600 meters \(1 mile\)/.test(r.body)]]){const r=play('propane',1,Object.assign({variant:v},o));report('mistakes',`refill cage: ${label} is caught and explained`,r.ok&&chk(r),`score ${r.score}`);}
  for(const [label,v,o,chk] of [['letting the through freight pass the leaking car',"A",{choiceAt:{trains:'bad'}},r=>r.score<=90&&/Right call: Take the train list and have the railroad stop every train/.test(r.body)&&/Trains and the train list/.test(r.body)],['having the switch crew pull the leaking car away',"C",{choiceAt:{trains:'bad'}},r=>r.score<=90&&/Wrong call/.test(r.body)],['climbing the car to close the valve (the Operations boundary)',"A",{choiceAt:{vapor:'ops'}},r=>r.score<=70&&/Hot-zone entry is not an Operations task: Climb the ladder and close the valve/.test(r.body)],['leaving the vapor to the team: named as a defensive action missed',"C",{choiceAt:{vapor:'missed'}},r=>r.score===95&&/Defensive actions missed:<\/b> Break the cloud up with fog from upwind/.test(r.body)],['leaving the ditch and culvert: named as a defensive action missed',"A",{choiceAt:{culvert:'missed'}},r=>r.score===95&&/Defensive actions missed:<\/b> Block the culvert and keep the vapor out of the ditch/.test(r.body)],['a straight stream on the dome housing',"A",{choiceAt:{vapor:'bad'}},r=>r.score<=90&&/Right call: Fog streams from upwind/.test(r.body)],['sheltering the elevator crew beside lit dryer burners',"A",{choiceAt:{elevator:'bad'}},r=>r.score<=90&&/Right call: Kill the dryer burners/.test(r.body)&&/The grain elevator/.test(r.body)],['letting the drivers at the crossing turn around in the cloud',"C",{choiceAt:{crossing:'bad'}},r=>r.score<=90&&/Right call: Close the road both ways/.test(r.body)],['a handline from the engine tank on the burning car with no water supply',"B",{choiceAt:{water:'bad'}},r=>r.score<=90&&/Right call: Pull everyone back, let it burn/.test(r.body)&&/No water supply/.test(r.body)],['a crew up the ladder under the flame (the Operations boundary)',"B",{choiceAt:{water:'ops'}},r=>r.score<=70&&/Hot-zone entry is not an Operations task: Send a crew up the ladder/.test(r.body)],['sheltering inside the fire distance, with the 1600 m line quoted from the table',"B",{choiceAt:{evac:'bad'}},r=>r.score<=90&&/Right call: Evacuate the full fire distance/.test(r.body)&&/1600 meters \(1 mile\)/.test(r.body)],['missing the reporting marks and the people in the size-up',"A",{binoMiss:true},r=>r.score<100&&r.score>=70]]){const r=play('rail',1,Object.assign({variant:v},o));report('mistakes',`rail car: ${label} is caught and explained`,r.ok&&chk(r),`score ${r.score}`);}
  for(const [label,v,o,chk] of [['telling the caller to bag the envelope and carry it out',"A",{choiceAt:{caller:'bad'}},r=>r.score<=90&&/Right call: Set it down, wash hands with soap and water/.test(r.body)&&/The caller/.test(r.body)],['trusting a clean 4-gas on a powder',"A",{choiceAt:{meter:'bad'}},r=>r.score<=90&&/Right call: A 4-gas cannot see a powder/.test(r.body)],['opening the envelope to field-test it (the Operations boundary)',"B",{choiceAt:{test:'ops'}},r=>r.score<=70&&/Hot-zone entry is not an Operations task: Open it up and run a field test/.test(r.body)],['leaving the air handling running: named as a defensive action missed',"A",{choiceAt:{hvac:'missed'}},r=>r.score===95&&/Defensive actions missed:<\/b> Shut the air handling off and close the room/.test(r.body)],['a fan to air the room out',"C",{choiceAt:{hvac:'bad'}},r=>r.score<=90&&/Right call: Shut the air handling off/.test(r.body)],['keeping the office at their desks',"A",{choiceAt:{building:'bad'}},r=>r.score<=90&&/Right call: Move everyone else out to an assembly point upwind/.test(r.body)],['finishing the outgoing bags at the parcel store',"B",{choiceAt:{sort:'bad'}},r=>r.score<=90&&/Right call: Stop the line/.test(r.body)],['leaving the coughing clerk in the room for the team',"C",{choiceAt:{sick:'bad'}},r=>r.score<=90&&/Right call: Talk her out, then flush her skin and eyes/.test(r.body)&&/The clerk with symptoms/.test(r.body)],['going in on air to carry the envelope to the hospital (the Operations boundary)',"C",{choiceAt:{sick:'ops'}},r=>r.score<=70],['sending the exposed people home',"A",{choiceAt:{exposed:'bad'}},r=>r.score<=90&&/Right call: Keep them together nearby/.test(r.body)],['picking up the envelope in the size-up',"A",{binoWrong:true},r=>r.score<100&&r.score>=80],['the clerk\'s name over the air',"A",{notifyExtra:true},r=>r.score<100]]){const r=play('powder',1,Object.assign({variant:v},o));report('mistakes',`white powder: ${label} is caught and explained`,r.ok&&chk(r),`score ${r.score}`);}
  for(const [label,v,o,chk] of [['going in on air to close the chlorine valve (the Operations boundary)',"A",{choiceAt:{valve:'ops'}},r=>r.score<=70&&/Chlorine burns skin and eyes through structural gear/.test(r.body)],['leaving the doorway vapor to the team: named as a defensive action missed',"A",{choiceAt:{valve:'missed'}},r=>r.score===95&&/Defensive actions missed:<\/b> Knock the vapor down at the doorway/.test(r.body)],['sending the kids to the downwind lot (layout A)',"A",{choiceAt:{deck:'bad'}},r=>r.score<=90&&/Right call: Clear the deck upwind/.test(r.body)&&/The pool deck/.test(r.body)],['walking the apartments out into the cloud (layout C: shelter)',"C",{choiceAt:{apts:'bad'}},r=>r.score<=90&&/Right call: Shelter them in place/.test(r.body)&&/protective distance is 0\.1 miles/.test(r.body)],['grab and go into the chlorine room for the second man (the Operations boundary, layout B)',"B",{choiceAt:{room:'ops'}},r=>r.score<=70&&/still a chlorine room/.test(r.body)&&/The second man/.test(r.body)],['moving staging to the door on a clean 4-gas',"A",{choiceAt:{meter:'bad'}},r=>r.score<=90&&/Right call: Nothing about chlorine/.test(r.body)]]){const r=play('pool',1,Object.assign({variant:v},o));report('mistakes',`swim club: ${label} is caught and explained`,r.ok&&chk(r),`score ${r.score}`);}
  for(const [label,v,o,chk] of [['searching a house above the LEL alarm (the Operations boundary, gas layout)',"B",{choiceAt:{meter:'ops'}},r=>r.score<=70&&/Above your alarm the house is the hot zone/.test(r.body)],['holding at the door for the hazmat team on a CO rescue (layout C: SCBA is full protection)',"C",{choiceAt:{rescue:'bad'}},r=>r.score<=90&&/Right call: Two in on air now/.test(r.body)&&/fire-service rescue, not a hazmat entry/.test(r.body)&&/The man in the bedroom/.test(r.body)],['leaving the gas meter for the utility: named as a defensive action missed',"B",{choiceAt:{source:'missed'}},r=>r.score===95&&/Defensive actions missed:<\/b> Shut the gas off at the meter outside/.test(r.body)],['an electric fan in a gas-filled doorway',"B",{choiceAt:{vent:'bad'}},r=>r.score<=90&&/A fan motor arcs/.test(r.body)&&/Ventilation/.test(r.body)],['going in after the cat with the meter (the Operations boundary)',"B",{choiceAt:{occupants:'ops'}},r=>r.score<=70&&/do not search a gas atmosphere for a pet/.test(r.body)],['letting the family back in for coats on a CO call',"A",{choiceAt:{occupants:'bad'}},r=>r.score<=90&&/Right call: Nobody back in/.test(r.body)],['never calling the utility on a house call (the house names the utility, not the hazmat team)',"A",{noTeam:true,notifySkipTeam:true},r=>r.score<=80&&/The gas utility was never requested/.test(r.body)&&/Gas utility requested/.test(r.body)]]){const r=play('house',1,Object.assign({variant:v},o));report('mistakes',`house: ${label} is caught and explained`,r.ok&&chk(r),`score ${r.score}`);}
  {const {boot}=require('./uw_mock.js');const {api,els}=boot();global.__T=1000;api.runStart('house');const btnH=els['uw-team'].textContent;api.runAct({r:'quit'});api.runStart('pool');const btnP=els['uw-team'].textContent;api.runAct({r:'quit'});report('mistakes','the always-available button reads "Call the gas utility" on the house call and "Call the team" everywhere else',btnH==='Call the gas utility · Isolate · Deny entry'&&btnP==='Call the team · Isolate · Deny entry');}
  {const {play}=require('./uw_bot.js');const B=play('i75',1,{variant:'B'});report('mistakes','layout B (large spill, night) adds the downwind evacuation decision and quotes the 1000-foot line from the table',B.ok&&B.score===100&&/Downwind evacuation/.test(B.body)&&(()=>{const b2=play('i75',1,{variant:'B',choiceAt:{evac:'bad'}});return b2.score<=90&&/Right call: Evacuate the truck stop now, out the crosswind side\. The guide says consider downwind evacuation for 1000 feet/.test(b2.body);})());
   const r=play('i75',0,{choiceAt:{drain:'ops',driver:'ops'},noTeam:true,notifySkipTeam:true,route:'down'});report('mistakes','the penalties stack and the score never goes below zero',r.ok&&r.score>=0&&r.score<=10,`score ${r.score}`);}}

if(want.includes('zones')){const {expected}=require('./zones.js');const {play}=require('./uw_bot.js');const {boot}=require('./uw_mock.js');const {api}=boot();for(const k in api.MAT)api.MAT[k].checked='t';api.runStart('i75');const S=api.S();let bad=0,n=0;
  for(let i=0;i<400;i++){const wind=Math.floor(Math.random()*360);const z={hot:25+Math.floor(Math.random()*16)*25,warm:25+Math.floor(Math.random()*24)*25,stage:{x:Math.random()*340,y:Math.random()*300}};const a=api.zoneFit(z,wind,150),e=expected(z,wind,150,S.R,S.scale);n++;if(a.ok!==e.ok||a.pen!==e.pen)bad++;}
  report('zones','zone fit agrees with an independent recalculation on 400 random settings (ok and penalty)',bad===0,`${bad} disagreements of ${n}`);
  {const g=api.plumeGeom();api.WX.dir=270;api.WX.mph=8;const down=api.conc(S.R.x+60,S.R.y),up=api.conc(S.R.x-60,S.R.y),side=api.conc(S.R.x+60,S.R.y+60);api.WX.mph=20;const narrow=api.plumeGeom().half;report('zones','the plume runs downwind only, thins to the side, and narrows as the wind picks up',down>.3&&up===0&&side<down&&narrow<g.half,`down ${down.toFixed(2)} up ${up} side ${side.toFixed(2)}`);}
  {api.WX.mph=8;const m1=api.meterAt({x:S.R.x+40,y:S.R.y}),m0=api.meterAt({x:S.R.x-80,y:S.R.y});report('zones','the meter sees LEL in the gasoline plume and nothing upwind; O₂, CO and H₂S stay clean',m1.lel>=10&&m0.lel===0&&m1.o2===20.9&&m1.co===0&&m1.h2s===0,`lel ${m1.lel}/${m0.lel}`);}}

if(want.includes('chaos')){const {play}=require('./uw_bot.js');const r=play('i75',2,{dwell:40});const S0=r.steps;report('chaos','on Chaos the wind shifts after 90 s, a second zones step is queued, and a crew that moves its zones still scores 100',r.ok&&r.score===100&&S0.filter(x=>x==='zones').length===2&&/Zones after the shift/.test(r.body),`steps ${S0.join(' ')} score ${r.score}`);
  {const {boot}=require('./uw_mock.js');const {api}=boot();for(const k in api.MAT)api.MAT[k].checked='t';global.__T=1000;api.runStart('i75');const d0=api.WX.dir;api.windShift((d0+90)%360,30);global.__T+=15;api.runTick();const mid=api.WX.dir;global.__T+=20;api.runTick();report('chaos','a wind shift takes real seconds, not a jump',Math.abs(((mid-d0+540)%360)-180)>0&&Math.abs(((mid-d0+540)%360)-180)<90&&api.WX.dir===(d0+90)%360&&api.WX.target===null,`${d0} → ${mid} → ${api.WX.dir}`);}
  {const skipBump=tier=>{const {boot}=require('./uw_mock.js');const {api}=boot();for(const k in api.MAT)api.MAT[k].checked='t';global.__T=1000;api.setTier(tier);api.runStart('i75');const S=api.S();global.__T+=1;api.runAct({r:'route',i:String(S.def.steps[0].routes.findIndex(r=>r.kind==='good'))});global.__T+=1;api.runTick();api.runAct({r:'opt',i:String(S.def.steps[1].o.findIndex(x=>x[1]==='bad'))});const v=api.vec((api.WX.dir+180)%360);const p={x:S.R.x+v.x*33,y:S.R.y+v.y*33};return {fault:S.sensorFault,lel:api.meterAt(p).lel,k:api.conc(p.x,p.y)};};const c=skipBump(2),r=skipBump(1);const dead=c.lel,live=r.lel;const S={sensorFault:c.fault};const api={conc:()=>c.k};const inPlume={};
   report('chaos','on Chaos a skipped bump test leaves a dead LEL sensor: the meter reads 0 in the plume (on Recall the same mistake only costs points)',S.sensorFault===true&&dead===0&&api.conc(inPlume.x,inPlume.y)>.3&&live>=10,`dead ${dead}, live ${live}`);}}

if(want.includes('inject')){const {boot}=require('./uw_mock.js');const {play}=require('./uw_bot.js');
  {const {api,els}=boot();for(const k in api.MAT)api.MAT[k].checked='t';global.__T=1000;const fab=els['inst-fab'];const hid=()=>fab.classList.contains('hidden');
   const a=hid();api.runStart('i75');const b=hid();api.runAct({r:'quit'});api.setInst(true);const c=hid();api.runStart('i75');const d=hid();
   report('inject','the Instructor button is hidden at home and during a run with the switch off, and shows during a run with it on',a&&b&&c&&!d);
   const S=api.S();global.__T+=5;api.runTick();const c1=els['run-clock'].textContent;api.instOpen();const open=!els.instov.classList.contains('hidden')&&/Inject now/.test(els['inst-body'].innerHTML)&&/Freeze and discuss/.test(els['inst-body'].innerHTML);
   global.__T+=30;api.runTick();api.runAct({r:'route',i:'0'});const frozen=els['run-clock'].textContent===c1&&S.frozenAt!==null&&S.i===0&&!S.st.done;
   api.instClose();global.__T+=0;api.runTick();report('inject','opening the sheet freezes the real clock and ignores taps; closing resumes with the frozen time removed (5 s in, 30 s frozen, clock still 0:05)',open&&frozen&&S.frozenAt===null&&els['run-clock'].textContent==='0:05'&&els.instov.classList.contains('hidden'),`clock ${els['run-clock'].textContent}`);
   api.windShift((api.WX.dir+90)%360,30);const d0=api.WX.dir;api.instOpen();global.__T+=20;api.runTick();const held=api.WX.dir===d0;api.instClose();global.__T+=15;api.runTick();report('inject','a wind shift in progress pauses with the freeze and carries on after it',held&&api.WX.target!==null&&api.WX.dir!==d0,`${d0} → ${api.WX.dir}`);
   api.instOpen();api.instAct('freeze');const h1=api.INSTHOLD()&&S.frozenAt!==null&&els.instov.classList.contains('hidden')&&fab.textContent==='Frozen — tap to resume';global.__T+=40;api.runTick();const t1=els['run-clock'].textContent;api.instOpen();const h2=!api.INSTHOLD()&&S.frozenAt===null&&fab.textContent==='Instructor';report('inject','Freeze and discuss holds the clock with the sheet closed; the button reads Frozen and tapping it resumes',h1&&h2&&els['run-clock'].textContent===t1,`clock ${t1}`);
   api.instOpen();api.runAct({r:'quit'});report('inject','Quit still works while frozen, and the button hides',api.S()===null&&fab.classList.contains('hidden'));}
  for(const [scn,at,id,chk] of [['i75','erg','wind',r=>true],['i75','drain','second',r=>r.steps.filter(x=>x==='zones').length===2&&/Zones after the shift|Zones/.test(r.body)],['i75','zones','victim',r=>r.steps.includes('decide:walkin')&&/Walk-in at the tape/.test(r.body)],['i75','bino','alarm',r=>true],['i75','traffic','delay',r=>r.steps.includes('decide:delay')&&/Team delayed/.test(r.body)],['nurse','fog','rain',r=>r.steps.includes('decide:rain')&&/Rain/.test(r.body)],['i75','driver','driver',r=>r.steps.includes('decide:walkback')&&/Back to the cab/.test(r.body)],['powder','test','mail',r=>r.steps.includes('decide:mail')&&/A second envelope/.test(r.body)]]){
   const r=play(scn,0,{variant:'A',injects:[{at,id}]});const run=JSON.parse(r.store.upwind).runs[0];const label=r.api.INJECTS.find(x=>x.id===id).label;
   report('inject',`${id} lands on ${scn} at the ${at} step: a crew that answers well still scores 100, the run is marked inst:1 and the debrief names the inject`,r.ok&&r.injected[0]===true&&r.score===100&&run.inst===1&&r.body.includes('Instructor injects:')&&r.body.includes(label)&&chk(r),`score ${r.score}, steps ${r.steps.join(' ')}`);}
  {const {boot}=require('./uw_mock.js');const {api}=boot();global.__T=1000;api.setInst(true);api.runStart('powder');const S=api.S();S.i=2;const offered=api.INJECTS.filter(x=>x.ok()).map(x=>x.id).sort().join();api.runAct({r:'quit'});api.runStart('i75');api.S().i=2;const out=api.INJECTS.filter(x=>x.ok()).map(x=>x.id);api.runAct({r:'quit'});report('inject','indoors the instructor sheet offers only the team delay and the second envelope; outdoors the second envelope is never offered',offered==='delay,mail'&&!out.includes('mail')&&out.includes('wind'),`indoor: ${offered}; outdoor: ${out.join()}`);}
  {const r=play('i75',1,{variant:'A',injects:[{at:'zones',id:'victim'}],choiceAt:{walkin:'ops'}});report('inject','chasing the walker into the cloud is the Operations boundary (−30) inside an injected step',r.ok&&r.score===70&&/Chasing him into the cloud is hot-zone entry/.test(r.body),`score ${r.score}`);}
  {const r=play('i75',2,{variant:'A',injects:[{at:'erg',id:'wind'}],dwell:40});report('inject','a wind inject on Chaos replaces the scripted shift (one shift, zones re-queued once, a crew that moves still scores 100)',r.ok&&r.score===100&&r.steps.filter(x=>x==='zones').length===2,`steps ${r.steps.join(' ')}`);}
  {const {api}=boot();for(const k in api.MAT)api.MAT[k].checked='t';global.__T=1000;api.setInst(true);api.runStart('i75');const S=api.S();api.runAct({r:'route',i:String(S.def.steps[0].routes.findIndex(r=>r.kind==='good'))});global.__T+=2;api.runTick();
   const one=api.inject('victim'),two=api.inject('delay');const pend=S.def.steps.filter(x=>x.inj).length;const alarmOK=api.INJECTS.find(x=>x.id==='alarm').ok();api.inject('alarm');const v=api.vec((api.WX.dir+180)%360);const p={x:S.R.x+v.x*30,y:S.R.y+v.y*30};const dead=api.meterAt(p).lel===0&&api.conc(p.x,p.y)>.3;
   api.runAct({r:'quit'});api.runStart('nurse');const nurseAlarm=api.INJECTS.find(x=>x.id==='alarm').ok();api.runAct({r:'quit'});
   report('inject','one spliced inject waits at a time; the dead-sensor inject is offered only where the meter reads the material (gasoline yes, ammonia no) and then the LEL reads zero in the plume',one&&!two&&pend===1&&alarmOK&&dead&&!nurseAlarm);}}

if(want.includes('smooth')){const {boot}=require('./uw_mock.js');const {api,els}=boot();for(const k in api.MAT)api.MAT[k].checked='t';global.__T=1000;api.setTier(0);api.runStart('i75');const S=api.S();api.runAct({r:'route',i:String(S.def.steps[0].routes.findIndex(r=>r.kind==='good'))});
  let rebuilds=0;const watch=id=>{const e=els[id];let v=e.innerHTML;Object.defineProperty(e,'innerHTML',{get:()=>v,set:x=>{if(x!==v)rebuilds++;v=x;}});};['uw-step','run-box','uw-foot','uw-map'].forEach(watch);
  for(let i=0;i<70;i++){global.__T+=.15;api.runTick();}report('smooth','nothing on the run screen is rebuilt while the player thinks (10 s of ticks, zero innerHTML writes); only attributes and text change',rebuilds===0,`${rebuilds} rebuilds`);
  {const before=els['uw-step'].innerHTML;api.runAct({r:'nudge',z:'hot',d:'25'});report('smooth','a nudge changes the zone and the map without rebuilding the buttons',els['uw-step'].innerHTML===before);}}


if(want.includes('real')){const {play}=require('./uw_bot.js');const {boot}=require('./uw_mock.js');
  // Graniteville 2005, the first Real Call: one fixed layout, the published record, ERG numbers only from MAT.
  {const {api,els}=boot();const M=api.MAT.chlorine,d=api.SCN.grani.build(api.VARIANTS.grani[0]);const t3=d.steps.find(x=>x.id==='table3');const txt=t3.o.map(o=>o[0]).join(' | ');
   // independent: the rows Max read in ERG2024 Table 3 (page 341) for a chlorine rail tank car, written here from his reading, not from MAT
   report('real','the isolation zone is the Table 3 chlorine rail-car row from MAT (3000 ft), and the row card quotes the night low (7.0+ mi) and moderate (5.6 mi) rows Max read, both accepted, with the day row and Table 1 as the wrong calls',d.isoFt===M.t3.rail.iso.ft&&d.isoFt===3000&&/protect 7\+ miles/.test(txt)&&/protect 5\.6 miles/.test(txt)&&/protect 3\.9 miles/.test(txt)&&/protect 0\.3 miles/.test(txt)&&t3.o.filter(o=>o[1]==='good').length===2&&t3.o.find(o=>o[1]==='good')[0].includes('low wind')&&d.plumeFixed&&d.plumeFt===Math.round(M.t3.rail.night.low*5280),txt);
   report('real','one fixed layout (south-southwest at 7, night, from the record); a Drill Night or a random pick always gets it; the home list shows it under Real Calls, enabled',api.VARIANTS.grani.length===1&&api.VARIANTS.grani[0].wind.mph===7&&api.VARIANTS.grani[0].wind.dir===202.5&&api.VARIANTS.grani[0].night===true&&/data-scn="grani"/.test(els.realcalls.innerHTML)&&!/data-scn="grani"[^>]*disabled/.test(els.realcalls.innerHTML)&&/Graniteville, South Carolina, 2005/.test(els.realcalls.innerHTML)&&!/grani/.test(els.incidents.innerHTML)&&/4 · Real Calls/.test(html));
   const b=d.steps[0];report('real','it opens on the briefing card with the sources (NTSB RAR-05/04, the CDC MMWR, Dunning and Oswalt) and a line saying the radio calls between the recorded times are modeled; Quit is there; the team button waits until after the approach',b.k==='brief'&&/RAR-05\/04/.test(b.h)&&/MMWR 2005;54\(03\)/.test(b.h)&&/Dunning and Oswalt/.test(b.h)&&/modeled/.test(b.h)&&/an estimated 46 to 60 of its 90 tons/.test(b.h)&&/a truck driver at one of the plant facilities/.test(b.h)&&/one person in a home south of the site/.test(b.h)&&!/asleep/.test(b.h)&&(()=>{global.__T=1000;api.runStart('grani');const ok=/Take the call/.test(els['uw-step'].innerHTML)&&els['uw-team'].classList.contains('hidden')&&/data-r="quit"/.test(html);api.runAct({r:'quit'});return ok;})());}
  for(const tier of [0,1,2]){const r=play('grani',tier);const run=JSON.parse(r.store.upwind).runs[0];
   report('real',`Graniteville on ${['Guided','Recall','Chaos'][tier]}: a crew that follows the record's best moves scores 100, never stands in the vapor, and the run is saved with no layout`,r.ok&&r.score===100&&run.id==='grani'&&run.variant===undefined&&run.tier===tier&&/Time in the vapor<\/td><td>0 s/.test(r.body)&&['brief','decide:standoff','decide:odor','approach','decide:meter','bino','erg','decide:table3','zones','decide:shelter','decide:down','decide:cp','decide:station','decide:decon','notify','decide:handoff'].every(x=>r.steps.includes(x))&&r.steps.filter(x=>x==='erg').length===2,`score ${r.score}, ${r.steps.length} steps`);}
  {const r=play('grani',2,{dwell:40});report('real','Chaos follows the record: no scripted wind shift on a Real Call, the zones step comes once, and a long run still scores 100',r.ok&&r.score===100&&r.steps.filter(x=>x==='zones').length===1&&r.api.WX.dir===202.5&&r.api.WX.target===null,`wind ${r.api.WX.dir}`);}
  {const r=play('grani',1,{pick:{table3:o=>o.findIndex(x=>x[1]==='good'&&/moderate/.test(x[0]))}});report('real','the moderate-wind night row is accepted too, and its feedback says when in doubt use the more protective row',r.ok&&r.score===100&&/The Table 3 row <span class="pc-detail">· Night, moderate wind: protect 5\.6 miles/.test(r.body)&&/When in doubt, use the more protective low-wind row/.test(r.api.SCN.grani.build(r.api.VARIANTS.grani[0]).steps.find(x=>x.id==='table3').o.find(o=>/moderate/.test(o[0])&&o[1]==='good')[2]),`score ${r.score}`);}
  {const r=play('grani',1,{choiceAt:{table3:'bad'}});report('real','a wrong Table 3 row costs 10 and the feedback names the low-wind night row as the right call',r.ok&&r.score===90&&/Right call: Night, low wind/.test(r.body),`score ${r.score}`);}
  {const r=play('grani',1,{choiceAt:{odor:'ops'}});report('real','driving on into the smell on air is the Operations boundary (−30), and the why says SCBA does not cover the skin or the cab',r.ok&&r.score===70&&/SCBA covers your lungs, not your skin or the cab/.test(r.body),`score ${r.score}`);}
  {const r=play('grani',1,{choiceAt:{shelter:'bad'}});report('real','evacuating by car at three in the morning costs 10; the feedback gives the right call and the record (2:49 reverse-911, 2:57 the one-mile buffer, the sheriff\'s evacuation later in the morning)',r.ok&&r.score===90&&/Right call: Shelter in place by reverse-911/.test(r.body)&&/At 2:49 the Graniteville fire department asked dispatch/.test(r.body)&&/later in the morning/.test(r.body),`score ${r.score}`);}
  {const r=play('grani',1,{choiceAt:{shelter:'missed'}});report('real','leaving protective action to the team is a defensive action missed, named in the debrief',r.ok&&r.score===95&&/Defensive actions missed:<\/b> Start shelter in place and close the roads into the valley/.test(r.body),`score ${r.score}`);}
  {const r=play('grani',1,{choiceAt:{shelter:'ops',down:'ops'}});report('real','door to door through the haze and going in for the person down by the cars are both the Operations boundary (−30 each)',r.ok&&r.score===40,`score ${r.score}`);}
  {const r=play('grani',1,{choiceAt:{cp:'bad',station:'bad'}});report('real','leaving the command post in the smell and staging mutual aid in the valley cost 10 each, and the feedback carries the record (3:39, the dealership; Station 1 lost to chlorine)',r.ok&&r.score===80&&/moved about a mile away at 3:39/.test(r.body)&&/two pumpers, a medical unit and a service truck/.test(r.body),`score ${r.score}`);}
  {const r=play('grani',1,{hot:330});report('real','a hot zone set to the Guide 111 or 124 line (330 ft) instead of the Table 3 rail row is short and costs points',r.ok&&r.score<100&&/hot zone short of the ERG distance/.test(r.body),`score ${r.score}`);}
  {const r=play('grani',1,{route:'down'});report('real','driving down into the valley is the downwind approach (−15)',r.ok&&r.score<=85&&/Approached from downwind/.test(r.body),`score ${r.score}`);}
  {const r=play('grani',0);const B=r.body;const has=['46 to 60 of its 90 tons','low-lying yellow haze that smelled like bleach','seventeen miles away: south-southwest at 7 mph, clear, 55°F','settled in the low-lying valley','At 2:42','at 2:48 reported being unable to breathe and withdrawing','Deputies who approached also had to withdraw','At 2:49','at 2:57 added road closures forming a one-mile buffer','car dealership, moved about a mile away at 3:39','A mill employee drove the injured conductor to the hospital','a motorist took the engineer','At 3:37 a mill supervisor went in with a firefighter to shut down the steam plant','a truck driver at one of the plant facilities','one person in a residence south of the site','Station 1 apparatus, two pumpers, a medical unit and a service truck','later in the morning','January 13 to 19','Safety Advisory 2005-01','Emergency Order No. 24','non-signaled territory','Norfolk Southern adopted a similar rule','vulnerability of tank cars','RAR-05/04'];
   const miss=has.filter(x=>!B.includes(x)),bad=['asleep','6:27','state emergency','midday','chlorine planning'].filter(x=>B.includes(x));
   report('real','the debrief tells the rest of the story from the NTSB report as Max checked it, and none of the dropped lines (asleep in the cab, 6:27, the state emergency at midday, community chlorine planning)',miss.length===0&&bad.length===0,miss.length?'missing: '+miss.join(' | '):bad.length?'present: '+bad.join(' | '):`${has.length} lines`);
   report('real','the debrief names the edition and Max\'s reading of the chlorine lines',/ERG2024, Guide 124, read on/.test(B));}
  {const {api,els}=boot();global.__T=1000;api.setInst(true);api.runStart('grani');const S=api.S();S.i=6;const offered=api.INJECTS.filter(x=>x.ok()).map(x=>x.id);const map=els['uw-map'].innerHTML;api.runAct({r:'quit'});
   report('real','instructor mode works on the Real Call, but the made-up driver inject is never offered; the map names the derailment, the mill, the homes in the low ground and the high ground',offered.includes('delay')&&!offered.includes('driver')&&/>DERAILMENT</.test(map)&&/>MILL</.test(map)&&/>HOMES · LOW GROUND</.test(map)&&/>HIGH GROUND</.test(map),offered.join(','));}
  {const {api,els}=boot();global.__T=1000;api.runStart('grani');let g=0;while(api.S().def.steps[api.S().i].k!=='bino'&&g++<20){const s=api.S().def.steps[api.S().i];global.__T+=1.2;api.runTick();if(s.k==='brief')api.runAct({r:'briefok'});else if(s.k==='approach')api.runAct({r:'route',i:String(s.routes.findIndex(x=>x.kind==='good'))});else{api.runAct({r:'opt',i:String(s.o.findIndex(x=>x[1]==='good'))});global.__T+=1.2;api.runAct({r:'next'});}}
   const h=els['uw-step'].innerHTML;api.runAct({r:'quit'});report('real','the binocular view shows no readable placard (the crews had none), and walking down to read one is the wrong tap',!/1203/.test(h)&&/yellowish haze/.test(h)&&api.SCN.grani.build(api.VARIANTS.grani[0]).steps.find(x=>x.k==='bino').items.find(x=>x.id==='walk').need===false);}
  {const {api}=boot();global.__T=1000;api.runStart('grani');const z=api.S().z,R=api.S().R,inPlume=api.conc(z.stage.x,z.stage.y);api.runAct({r:'quit'});report('real','on the wide map the zone rings start apart (1500 and 2250 ft, so a finger can grab the hot handle) with ±250 ft buttons, and staging starts upwind out of the plume',z.hot===1500&&z.warm===2250&&inPlume===0&&api.SCN.grani.build(api.VARIANTS.grani[0]).nudge===250,`hot ${z.hot}, warm ${z.warm}, plume at staging ${inPlume}`);}
  {const {api,els,store}=boot({upwind:JSON.stringify({runs:[{kind:'scenario',id:'grani',score:90,d:'2026-10-06T10:00:00.000Z',tier:1}]})});els['h-prog'].onclick();els['p-csv'].onclick();
   report('real','progress lists Real Calls and the CSV names the run',/REAL CALLS/.test(els['info-b'].innerHTML)&&/Graniteville, South Carolina, 2005/.test(global.__csv)&&api.readiness().done===1&&/id="chip-grani">90</.test(els.realcalls.innerHTML));}}

if(want.includes('real')){const {play}=require('./uw_bot.js');const {boot}=require('./uw_mock.js');
  // Kingman 1973, the second Real Call: the City of Kingman Fire Department's page is the primary source; no clock time for the failure, the wind is modeled.
  {const {api,els}=boot();const M=api.MAT.propane,d=api.SCN.king.build(api.VARIANTS.king[0]);const B=d.steps[0].h,R=d.record.h,all=JSON.stringify(d.steps.map(x=>[x.p,x.h,x.o,x.items,x.opts,x.why]))+R;
   report('real','Kingman: isolation is the guide\'s tank-in-fire distance from MAT (1600 m, about a mile), and the ERG step quotes Guide 115\'s lines from MAT',d.isoFt===Math.round(M.fire.m*3.28084/10)*10&&d.isoFt>5000&&d.isoFt<5300&&/Guide 115/.test(d.steps.find(x=>x.k==='erg').why)&&d.steps.find(x=>x.k==='erg').why.includes(M.fire.txt)&&d.steps.find(x=>x.k==='zones').p.includes(M.fire.txt),`iso ${d.isoFt} ft`);
   report('real','Kingman: no clock time for the failure (no 2:10), the failure comes about seventeen minutes after arrival, the wind is marked modeled, and no NTSB citation',!/2:10/.test(all)&&/About seventeen minutes after you arrived, the tank car failed/.test(d.steps[d.steps.length-1].hf.toString())&&/the wind on the map is modeled/.test(api.VARIANTS.king[0].name)&&/modeled/.test(B)&&!/NTSB/.test(all)&&!/west wind/i.test(all)&&!/iafc/i.test(all));
   const has=['around 1:30 p.m.','While workers tried to stop a leak at a fitting, the propane ignited','rail tank car 38214, about 33,000 gallons, on a spur leased from the Santa Fe','flames seventy to eighty feet long','called at 1:57 p.m. and was on scene three minutes later','over 100°F','booster tank within about two minutes','the deluge gun was not ready in time','about 200 yards away across the open desert','roadblocks were being set about a thousand feet out','An order to move people back had just been given','about twenty minutes after the first call','Eleven Kingman firefighters, two career and nine volunteer, and one civilian died','Three firefighters died at the scene and eight over the following week','More than 100 people were hurt','more than two thousand feet','a two-ton tank end landed about a quarter mile down the spur','10-foot crater','bulk storage tanks to be diked and protected by foam systems','rail spurs to be placed in pits','Kingman\'s films have been used in training','In memory of the eleven Kingman firefighters','cityofkingman.gov/government/departments-a-h/fire-department/bleve-memorial','City of Kingman Fire Department, BLEVE/Memorial (the primary source)'];
   const miss=has.filter(x=>!R.includes(x)),bad=['wrench','2:10','three-ton','12 mph','thirteen','twelve firefighters','insulation','95 people','NTSB'].filter(x=>all.includes(x));
   report('real','Kingman: the debrief carries the record as Max checked it (24 lines) and none of the dropped details (the wrench, 2:10, three-ton, the wind, other death counts, insulation, NTSB); no firefighter is named',miss.length===0&&bad.length===0&&!/\b(Casson|Myron|Hubka|Chambers|Marvin|Stringer|Sanders|Richard Lee|Frank S|Campbell|Webb)\b/.test(all),miss.length?'missing: '+miss.join(' | '):bad.length?'present: '+bad.join(' | '):'ok');
   const cool=d.steps.find(x=>x.id==='cool');report('real','Kingman: the handline choice is scored wrong with Max\'s sentence first; unmanned streams and withdraw-and-let-it-burn are both right; going in under the flame is the boundary',cool.o.find(o=>o[1]==='bad')[2].startsWith('Kingman\'s crews did everything they could with what they had, and were setting up unmanned nozzles when the tank failed. Their loss is why today\'s guidance says: unmanned streams from a distance, or withdraw.')&&cool.o.filter(o=>o[1]==='good').length===2&&cool.o.some(o=>o[1]==='ops'));
   report('real','Kingman: listed under Real Calls with Graniteville, enabled',/data-scn="king"/.test(els.realcalls.innerHTML)&&!/data-scn="king"[^>]*disabled/.test(els.realcalls.innerHTML)&&api.VARIANTS.king.length===1);}
  for(const tier of [0,1,2]){const r=play('king',tier);const run=JSON.parse(r.store.upwind).runs[0];
   report('real',`Kingman on ${['Guided','Recall','Chaos'][tier]}: unmanned streams, withdraw, the mile and the crowd back scores 100; the failure always comes, one plain line, and the debrief says crews and crowd were out`,r.ok&&r.score===100&&run.id==='king'&&run.variant===undefined&&r.steps[r.steps.length-1]==='brief'&&/Crews when the tank failed<\/td><td>Back, unmanned streams only/.test(r.body)&&/The crowd when the tank failed<\/td><td>Back at the mile/.test(r.body)&&/What happened at Kingman/.test(r.body),`score ${r.score}`);}
  {const r=play('king',2,{dwell:40});report('real','Kingman on Chaos follows the record: no wind shift',r.ok&&r.score===100&&r.api.WX.dir===270&&r.api.WX.target===null);}
  {const r=play('king',1,{pick:{cool:o=>o.findIndex(x=>x[1]==='good'&&/let it burn/.test(x[0]))}});report('real','Kingman: withdrawing and letting it burn is accepted too',r.ok&&r.score===100,`score ${r.score}`);}
  {const r=play('king',1,{choiceAt:{cool:'bad',crowd:'bad'}});report('real','Kingman: crews on handlines and the crowd left at the roadblocks cost 10 each, the right call is named, and the debrief says where people were when the tank failed',r.ok&&r.score===80&&/Right call: Set unmanned master streams/.test(r.body)&&/Still close to the car/.test(r.body)&&/Inside the mile/.test(r.body),`score ${r.score}`);}
  {const r=play('king',1,{choiceAt:{cool:'ops'}});report('real','Kingman: going in under the flame is the Operations boundary (−30)',r.ok&&r.score===70,`score ${r.score}`);}
  {const r=play('king',1,{hot:330});report('real','Kingman: an isolation ring at the leak distance (330 ft) instead of the mile costs points',r.ok&&r.score<100&&/hot zone short of the ERG distance/.test(r.body),`score ${r.score}`);}
  {const {api,els}=boot();global.__T=1000;api.setInst(true);api.runStart('king');api.S().i=4;const off=api.INJECTS.filter(x=>x.ok()).map(x=>x.id);const map=els['uw-map'].innerHTML;api.runAct({r:'quit'});report('real','Kingman: no made-up driver inject; the map names the tank car, the plant, the spur and Route 66',!off.includes('driver')&&/>TANK CAR 38214</.test(map)&&/>DOXOL PLANT</.test(map)&&/>ROUTE 66</.test(map)&&/>SPUR</.test(map),off.join(','));}}

if(want.includes('real')){const {play}=require('./uw_bot.js');const {boot}=require('./uw_mock.js');
  // East Palestine 2023, the third Real Call: only the NTSB's findings (RIR-24/05; the bearing readings and evacuation areas from RRD23MR005), as Max reviewed them on October 6, 2026.
  {const {api,els}=boot();const M=api.MAT.vcm,d=api.SCN.epal.build(api.VARIANTS.epal[0]);const B=d.steps[0].h,R=d.record.h,all=JSON.stringify(d.steps.map(x=>[x.p,x.h,x.o,x.items,x.opts,x.why,x.radio]))+R+api.VARIANTS.epal[0].name;
   const ergs=d.steps.filter(x=>x.k==='erg');
   report('real','East Palestine: isolation is Guide 116P\'s tank-in-fire distance from MAT (1600 m, about a mile); the ERG steps go Guide 111 with nothing identified, then 116P with its isolate, large-spill and fire lines read from MAT',d.isoFt===Math.round(M.fire.m*3.28084/10)*10&&ergs.length===2&&/Guide 111/.test(ergs[0].opts.find(o=>o[1]==='good')[0])&&ergs[1].opts.find(o=>o[1]==='good')[0].startsWith('Guide '+M.guide)&&M.guide==='116P'&&ergs[1].why.includes(M.iso.ft+' feet')&&ergs[1].why.includes(M.large.txt)&&ergs[1].why.includes(M.fire.txt)&&d.steps.find(x=>x.k==='zones').p.includes(M.fire.txt)&&d.mats.every(k=>api.MAT[k].checked),`iso ${d.isoFt} ft`);
   const has=['about 8:54 p.m.','train 32N, 149 cars, derailed 38 cars at milepost 49.5','Eleven of the derailed cars carried hazardous materials','a defective wheel bearing caused the derailment','38, then 103, then 253 degrees above the outside air','about four hundred feet from the derailment, inside the hot zone, and was later moved','faulted the command post\'s closeness and the use of hoselines near a fire of unknown materials','fire-damaged, illegible placards as a safety issue','About two thousand residents within a mile were evacuated','one mile by two miles','"(1) NS\'s delay in transmitting the train consist information to emergency responders and (2) the state of Ohio\'s insufficient training requirements for volunteer firefighters."','The finding concerned the state\'s training requirements, not the effort of the volunteers.','The train list must reach responders immediately','stabilized and were cooling, and nothing showed that polymerization was occurring','rejected three other ways of removing the vinyl chloride','on the afternoon of February 6','"based on incomplete and misleading information provided by Norfolk Southern officials and contractors,"','"not necessary to prevent a tank car failure."','The manufacturer\'s experts\' view that polymerization was not occurring never reached the incident commander','the incident commander, the village\'s fire chief','Norfolk Southern disagreed with the NTSB\'s conclusions about the vent and burn.','No one died.','dozens of new safety recommendations','Railroad Investigation Report NTSB/RIR-24/05','Norfolk Southern Railway Derailment and Hazardous Materials Release, East Palestine, Ohio, February 3, 2023','preliminary report RRD23MR005'];
   const miss=has.filter(x=>!R.includes(x));
   const dropped=['9:04','9:45','2 a.m.','2:00','conductor','13 minutes','thirteen minutes','4:37','February 4','February 8','not invited','invited','138','oxygen','31 ','thirty-one','34 ','good faith','venting stopped','returned home','settlement','lawsuit','litigation','governor','DeWine','Shapiro','Buttigieg','EPA','politic'];
   const bad=dropped.filter(x=>all.toLowerCase().includes(x.toLowerCase()));
   report('real','East Palestine: the debrief carries the NTSB findings as Max approved them (26 lines, both quotations verbatim, Norfolk Southern\'s disagreement) and none of the dropped details (the train-list clock times, the conductor as an event, the decision window, 4:37, when venting stopped, the return home, not invited, temperature and oxygen figures, 31 recommendations), no politics and no litigation',miss.length===0&&bad.length===0,miss.length?'missing: '+miss.join(' | '):bad.length?'present: '+bad.join(' | '):'ok');
   report('real','East Palestine: nobody is named (the incident commander is "the village\'s fire chief"), the wind is marked modeled, and the briefing names the NTSB report and says the radio calls between are modeled',!/\b(Drabick|Keith|Homendy|Conaway|Shaw)\b/.test(all)&&/the wind on the map is modeled/.test(api.VARIANTS.epal[0].name)&&/modeled/.test(B)&&/RIR-24\/05/.test(B)&&/RRD23MR005/.test(B)&&/No one died/.test(B));
   const bino=d.steps.find(x=>x.k==='bino');report('real','East Palestine: the binoculars show the placards fire-damaged and unreadable (the NTSB\'s safety issue), and walking up to read one is the wrong tap',bino.items.some(x=>x.need&&/burned beyond reading/.test(x.label)&&/fire-damaged, illegible placards/.test(x.why))&&bino.items.some(x=>!x.need&&/read a placard/.test(x.label))&&d.binoArt.noPlacard);
   const con=d.steps.find(x=>x.id==='consist');report('real','East Palestine: the train list is taught as general knowledge (the train crew carries it; ask the railroad and keep asking), both right, with the NTSB finding that it must reach responders immediately; waiting for it is wrong',con.o.filter(o=>o[1]==='good').length===2&&/train crew carries the consist/.test(con.o[0][2])&&con.o.filter(o=>o[1]==='good').every(o=>/must reach responders immediately/.test(o[2])));
   const mon=d.steps[d.steps.length-1];report('real','East Palestine: the last card is Monday, February 6, a reflective "what would you ask for" question that never judges the incident commander: the manufacturer\'s chemists and the temperature trend, with the NTSB finding',mon.id==='monday'&&mon.reflect===true&&/If you were at the table, what would you ask for first\?/.test(mon.p)&&/manufacturer's chemists/.test(mon.o.find(o=>o[1]==='good')[0])&&!/incident commander (should|failed|was wrong|erred)/i.test(JSON.stringify(mon)));
   report('real','East Palestine: the P card teaches polymerization and the trend card a temperature that keeps climbing',/polymerize/.test(d.steps.find(x=>x.id==='pmark').o.find(o=>o[1]==='good')[0])&&/keeps climbing/.test(d.steps.find(x=>x.id==='ptrend').o.find(o=>o[1]==='good')[0]));
   report('real','East Palestine: listed under Real Calls with Graniteville and Kingman, enabled; one fixed layout',/data-scn="epal"/.test(els.realcalls.innerHTML)&&!/data-scn="epal"[^>]*disabled/.test(els.realcalls.innerHTML)&&api.VARIANTS.epal.length===1);}
  for(const tier of [0,1,2]){const r=play('epal',tier);const run=JSON.parse(r.store.upwind).runs[0];
   report('real',`East Palestine on ${['Guided','Recall','Chaos'][tier]}: stand off, get the list, both guides, the mile, evacuate, feed it up, and ask for the chemists scores 100, saved with no layout`,r.ok&&r.score===100&&run.id==='epal'&&run.variant===undefined&&/What happened at East Palestine/.test(r.body),`score ${r.score}`);}
  {const r=play('epal',2,{dwell:40});report('real','East Palestine on Chaos follows the record: no wind shift',r.ok&&r.score===100&&r.api.WX.dir===250&&r.api.WX.target===null);}
  {const r=play('epal',1,{pick:{consist:o=>o.findIndex(x=>x[1]==='good'&&/dispatch call the railroad/.test(x[0]))}});report('real','East Palestine: having dispatch call the railroad for the list is accepted too',r.ok&&r.score===100,`score ${r.score}`);}
  {const r=play('epal',1,{choiceAt:{monday:'bad'}});const {api,els}=boot();global.__T=1000;api.runStart('epal');const S=api.S();S.i=S.def.steps.findIndex(x=>x.id==='monday');S.st={};S.guard=0;global.__T+=2;api.runTick();const s=S.def.steps[S.i];api.runAct({r:'opt',i:String(s.o.findIndex(o=>o[1]==='bad'))});const line=els['uw-now'].innerHTML,sc=S.score;api.runAct({r:'quit'});
   report('real','East Palestine: the Monday card is reflective: another answer costs nothing, no "Wrong call", and the feedback names what is worth asking first with the NTSB finding',r.ok&&r.score===100&&sc===100&&/Worth asking first:/.test(line)&&/manufacturer/.test(line)&&!/Wrong call/.test(line),`score ${r.score}, ${sc}`);}
  {const r=play('epal',1,{choiceAt:{standoff:'bad',consist:'bad',evac:'bad',feedup:'bad'}});report('real','East Palestine: a close command post, waiting on placards, sheltering inside the mile and holding the list back cost 10 each, and the right call is named',r.ok&&r.score===60&&/Right call: Command well back and upwind/.test(r.body)&&/Right call: Evacuate everyone within the mile/.test(r.body),`score ${r.score}`);}
  {const r=play('epal',1,{choiceAt:{standoff:'ops'}});report('real','East Palestine: sending a crew in close to read placards in the fire is the Operations boundary (−30)',r.ok&&r.score===70,`score ${r.score}`);}
  {const r=play('epal',1,{choiceAt:{pmark:'bad',ptrend:'bad'}});report('real','East Palestine: misreading the P or the signs of a reaction costs 10 each',r.ok&&r.score===80,`score ${r.score}`);}
  {const r=play('epal',1,{hot:330});report('real','East Palestine: an isolation ring at the leak distance (330 ft) instead of the mile costs points',r.ok&&r.score<100&&/hot zone short of the ERG distance/.test(r.body),`score ${r.score}`);}
  {const {api,els}=boot();global.__T=1000;api.setInst(true);api.runStart('epal');api.S().i=4;const off=api.INJECTS.filter(x=>x.ok()).map(x=>x.id);const map=els['uw-map'].innerHTML;api.runAct({r:'quit'});report('real','East Palestine: no made-up driver inject; the map names the derailment, the main line, the homes and the village',!off.includes('driver')&&/>DERAILMENT</.test(map)&&/>MAIN LINE</.test(map)&&/>HOMES</.test(map)&&/>EAST PALESTINE</.test(map),off.join(','));}}

{const {api}=boot();const subs=[...api.PLAN.scn,...api.PLAN.real].map(x=>x[2]);const cut=subs.filter(s=>/\b(the|a|an|and|of|to)\s+\S{1,2}$|\b[A-Z]$/.test(s));
 report('home','every incident and Real Call subtitle reads as a whole phrase (Max read "the train list and the P" as cut off)',cut.length===0&&api.PLAN.real.find(x=>x[0]==='epal')[2]==='Vinyl chloride in a derailment fire · getting the facts to command',cut.join(' | '));}

console.log(`\n${n-failed}/${n} checks passed · ${Math.round((Date.now()-T0)/1000)} s`);process.exit(failed?1:0);
